import type { LucideIcon } from "lucide-react";
import {
  Banknote,
  Bike,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Camera,
  Car,
  ChefHat,
  CircuitBoard,
  Clapperboard,
  Coffee,
  Cpu,
  Dumbbell,
  Factory,
  Flower2,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  HeartPulse,
  Home,
  Hotel,
  Landmark,
  Laptop,
  Leaf,
  Megaphone,
  Mic,
  MonitorSmartphone,
  Music,
  Package,
  Palette,
  PawPrint,
  Pill,
  Plane,
  Printer,
  Recycle,
  Scale,
  Scissors,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Truck,
  Utensils,
  UtensilsCrossed,
  Warehouse,
  Wrench,
  Wifi,
  Code2,
} from "lucide-react";

export type CategoryIconOption = {
  name: string;
  label: string;
  Icon: LucideIcon;
};

/** Canonical icon names stored in `categories.icon_name` (~50 business-relevant). */
export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = [
  { name: "utensils", label: "Restoran", Icon: Utensils },
  { name: "utensilscrossed", label: "F&B", Icon: UtensilsCrossed },
  { name: "chefhat", label: "Kuliner", Icon: ChefHat },
  { name: "coffee", label: "Kafe", Icon: Coffee },
  { name: "code2", label: "Software", Icon: Code2 },
  { name: "cpu", label: "Teknologi", Icon: Cpu },
  { name: "laptop", label: "IT / Software", Icon: Laptop },
  { name: "circuitboard", label: "Elektronik", Icon: CircuitBoard },
  { name: "smartphone", label: "Mobile", Icon: Smartphone },
  { name: "monitorsmartphone", label: "Digital", Icon: MonitorSmartphone },
  { name: "wifi", label: "Jaringan / ISP", Icon: Wifi },
  { name: "printer", label: "Percetakan", Icon: Printer },
  { name: "briefcase", label: "Bisnis / B2B", Icon: Briefcase },
  { name: "building2", label: "Perusahaan", Icon: Building2 },
  { name: "landmark", label: "Bank / Finansial", Icon: Landmark },
  { name: "banknote", label: "Keuangan", Icon: Banknote },
  { name: "calculator", label: "Akuntansi", Icon: Calculator },
  { name: "scale", label: "Legal / Hukum", Icon: Scale },
  { name: "gavel", label: "Pengadilan", Icon: Gavel },
  { name: "shield", label: "Asuransi / Security", Icon: Shield },
  { name: "heartpulse", label: "Kesehatan", Icon: HeartPulse },
  { name: "stethoscope", label: "Klinik / Medis", Icon: Stethoscope },
  { name: "pill", label: "Farmasi", Icon: Pill },
  { name: "dumbbell", label: "Fitness", Icon: Dumbbell },
  { name: "graduationcap", label: "Pendidikan", Icon: GraduationCap },
  { name: "bookopen", label: "Kursus / Buku", Icon: BookOpen },
  { name: "shoppingbag", label: "Retail", Icon: ShoppingBag },
  { name: "store", label: "Toko", Icon: Store },
  { name: "package", label: "E-commerce", Icon: Package },
  { name: "boxes", label: "Gudang / Supply", Icon: Boxes },
  { name: "warehouse", label: "Warehousing", Icon: Warehouse },
  { name: "truck", label: "Logistik", Icon: Truck },
  { name: "ship", label: "Ekspor / Shipping", Icon: Ship },
  { name: "sparkles", label: "Kreatif", Icon: Sparkles },
  { name: "palette", label: "Desain", Icon: Palette },
  { name: "camera", label: "Fotografi", Icon: Camera },
  { name: "clapperboard", label: "Film / Produksi", Icon: Clapperboard },
  { name: "megaphone", label: "Marketing", Icon: Megaphone },
  { name: "mic", label: "Podcast / Event", Icon: Mic },
  { name: "headphones", label: "Audio", Icon: Headphones },
  { name: "music", label: "Musik", Icon: Music },
  { name: "gamepad2", label: "Gaming", Icon: Gamepad2 },
  { name: "home", label: "Properti", Icon: Home },
  { name: "hotel", label: "Hospitality", Icon: Hotel },
  { name: "car", label: "Otomotif", Icon: Car },
  { name: "bike", label: "Sepeda / Mobility", Icon: Bike },
  { name: "bus", label: "Transportasi", Icon: Bus },
  { name: "plane", label: "Travel / Aviation", Icon: Plane },
  { name: "fuel", label: "Energi / BBM", Icon: Fuel },
  { name: "hammer", label: "Konstruksi", Icon: Hammer },
  { name: "wrench", label: "Servis / Bengkel", Icon: Wrench },
  { name: "factory", label: "Manufaktur", Icon: Factory },
  { name: "leaf", label: "Agri / Green", Icon: Leaf },
  { name: "flower2", label: "Florist", Icon: Flower2 },
  { name: "recycle", label: "Daur ulang", Icon: Recycle },
  { name: "shirt", label: "Fashion", Icon: Shirt },
  { name: "scissors", label: "Salon / Barber", Icon: Scissors },
  { name: "gem", label: "Perhiasan", Icon: Gem },
  { name: "pawprint", label: "Pet care", Icon: PawPrint },
  { name: "handheart", label: "Nonprofit / CSR", Icon: HandHeart },
];

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  CATEGORY_ICON_OPTIONS.map(({ name, Icon }) => [name, Icon]),
);

// Aliases for older / alternate spellings
ICON_MAP.building = Building2;

export function getCategoryIcon(iconName?: string | null): LucideIcon {
  if (!iconName) return Building2;
  const key = iconName.replace(/[-_\s]/g, "").toLowerCase();
  return ICON_MAP[key] ?? Building2;
}
